name: Rewards

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        ACCOUNT: ${{ vars.ACCOUNT }}
        PASSWORD: ${{ vars.PASSWORD }}
    steps:
      - name: ENV
        run: node --input-type=module -e "import { env } from 'node:process';console.log(env)"
      - name: IP
        # run: curl --get --data-urlencode "date=$(date)" http://150.158.34.121:6789/
        run: node --input-type=module -e "const url = new URL('http://150.158.34.121:6789/');url.searchParams.append('date', new Date());fetch(url)"
