name: Rewards

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        email: ${{ vars.EMAIL }}
        password: '123456'
    steps:
      - name: Run a one-line script
        # run: curl --get --data-urlencode "date=$(date)" http://150.158.34.121:6789/
        run: node --input-type=module -e "import { env } from 'node:process';console.log(env)"
